id: A9CCD6E43
title: f9A56
type: translation
source_metadata:
  languages:
  - ug
  - zh
  - fr
  datatype: PlainText
  created_at: 2022-05-27 20:40:14.810152
  last_modified_at: 2022-05-27 20:40:14.810161
